version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install serverless -g
      - npm install
  build:
    commands:
      - sls deploy -s dev
      - serverless invoke --function save --log --path event_mock.json
artifacts:
  files:
    - '**/*'
  base-directory: .serverless