service: nclouds-demo
app: poc
org: emilionclouds

frameworkVersion: '2'

custom:
  bucket: ${self:service}-${self:provider.stage}-saved
  ecr-poc: ${self:service}-${self:provider.stage}-poc
  ecr-app: ${self:service}-${self:provider.stage}-app

provider:
  name: aws
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
  ecr:
    images:
      poc-image:
        path: ./poc-image
      appimage:
        path: ./appimage

functions:
  save:
    image:
      name: poc-image
    environment:
      BUCKET: ${self:custom.bucket}
  text:
    image:
      name: appimage
    events:
      - http:
          path: ping
          method: get

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
    ECRPoc:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.ecr-poc}
        ImageScanningConfiguration:
          ScanOnPush: "true"
    ECRApp:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: ${self:custom.ecr-app}
        ImageScanningConfiguration:
          ScanOnPush: "true"
